setGeneric('nextResults', function(x, ...) standardGeneric('nextResults'))
setGeneric('undoQuery', function(x, ...) standardGeneric('undoQuery'))
setGeneric('resetQuery', function(x, ...) standardGeneric('resetQuery'))
setGeneric('resetSelect', function(x, ...) standardGeneric('resetSelect'))
setGeneric('per_page', function(x, ...) standardGeneric('per_page'))
setGeneric('viewProjects', function(x, ...) standardGeneric('viewProjects'))
setGeneric('getManifest', function(x, ...) standardGeneric('getManifest'))
setGeneric('getManifestFileFormats', function(x, ...) standardGeneric('getManifestFileFormats'))
setGeneric('results', function(x, ...) standardGeneric('results'))
setGeneric('downloadExpressionMatrices', function(x, ...) standardGeneric('downloadExpressionMatrices'))
setGeneric('checkExpressionMatricesAvailability', function(x, ...) standardGeneric('checkExpressionMatricesAvailability'))

